name: disaster-response
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - scikit-learn
  - sqlite
  - plotly
  - nltk
  - sqlalchemy
  - flask
  - dash
  - dash-core-components
  - dash-html-components
  - dash-bootstrap-components
